# This code plots four figures in the same canvas.
electric <- read.table("household_power_consumption.txt",
                       skip=66637,nrows=2880,sep=";")
day = strptime(paste(electric[,"V1"],electric[,"V2"]), "%d/%m/%Y %T")
png("plot4.png",width=480,height=480)
par(mfcol=c(2,2))
plot(day,electric[,"V3"],xlab="",ylab="Global Active Power",type="l")
plot(day,electric[,"V7"],xlab="",ylab="Energy sub metering",type="l")
lines(day,electric[,"V8"],col="red")
lines(day,electric[,"V9"],col="blue")
legend("topright",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3")
       ,col=c("black","red","blue"),lty=1,bty="n")
plot(day,electric[,"V5"],xlab="datetime",ylab="Voltage",type="l")
plot(day,electric[,"V4"],xlab="datetime",ylab="Global_reactive_power",type="l")
dev.off()